VERBOSE: True

MODEL:
  SESSION: 'Model'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 300
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  PS_W: 128
  PS_H: 128
  TRAIN_FILE: '../dataset/FFHQ.npz' # path to training data
  VAL_FILE: '../dataset/ASFW.npz'     # path to validation data
  SAVE_DIR: './checkpoints/'          # path to save models and images
  ORI: False

TESTING:
  WEIGHT: './checkpoints/RDD_epoch_178.pth'
  SAVE_IMAGES: True